### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Ainali**
Same as the rest of the project

### CODE REVIEW

**Comment by Abbe98** [comment]
The provided LICENSE file, is just a template, aka it do not provide author or a copyright year.

**Comment by Ainali** [comment]
Ahh, missed that. Should we use something like following?
Kyrksok.se  Copyright (C) 2016  Kyrksök

**Comment by Abbe98** [comment]
For the API I added my own name, as I'm a legal person. In this case were the repo has multiply contributors we might need something like "Kyrksok.se Copyright (C) 2016 Kyrksök contributors"

**Comment by Ainali** [comment]
Sounds good.

**Pull request merged**
